// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: protos/crawler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_protos_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_protos_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *FetchResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_protos_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_protos_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_protos_crawler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_crawler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_protos_crawler_proto_rawDescGZIP(), []int{2}
}

func (x *ParseRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_protos_crawler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_crawler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_protos_crawler_proto_rawDescGZIP(), []int{3}
}

func (x *ParseResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_protos_crawler_proto protoreflect.FileDescriptor

const file_protos_crawler_proto_rawDesc = "" +
	"\n" +
	"\x14protos/crawler.proto\x12\rsecurecrawler\"#\n" +
	"\rFetchResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\" \n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\"\n" +
	"\fParseRequest\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"#\n" +
	"\rParseResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls2T\n" +
	"\x0eFetcherService\x12B\n" +
	"\x05Fetch\x12\x1b.securecrawler.FetchRequest\x1a\x1c.securecrawler.FetchResponse2S\n" +
	"\rParserService\x12B\n" +
	"\x05Parse\x12\x1b.securecrawler.ParseRequest\x1a\x1c.securecrawler.ParseResponseB*Z(github.com/gedrodot/secure-crawler/protob\x06proto3"

var (
	file_protos_crawler_proto_rawDescOnce sync.Once
	file_protos_crawler_proto_rawDescData []byte
)

func file_protos_crawler_proto_rawDescGZIP() []byte {
	file_protos_crawler_proto_rawDescOnce.Do(func() {
		file_protos_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_crawler_proto_rawDesc), len(file_protos_crawler_proto_rawDesc)))
	})
	return file_protos_crawler_proto_rawDescData
}

var file_protos_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_crawler_proto_goTypes = []any{
	(*FetchResponse)(nil), // 0: securecrawler.FetchResponse
	(*FetchRequest)(nil),  // 1: securecrawler.FetchRequest
	(*ParseRequest)(nil),  // 2: securecrawler.ParseRequest
	(*ParseResponse)(nil), // 3: securecrawler.ParseResponse
}
var file_protos_crawler_proto_depIdxs = []int32{
	1, // 0: securecrawler.FetcherService.Fetch:input_type -> securecrawler.FetchRequest
	2, // 1: securecrawler.ParserService.Parse:input_type -> securecrawler.ParseRequest
	0, // 2: securecrawler.FetcherService.Fetch:output_type -> securecrawler.FetchResponse
	3, // 3: securecrawler.ParserService.Parse:output_type -> securecrawler.ParseResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_crawler_proto_init() }
func file_protos_crawler_proto_init() {
	if File_protos_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_crawler_proto_rawDesc), len(file_protos_crawler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protos_crawler_proto_goTypes,
		DependencyIndexes: file_protos_crawler_proto_depIdxs,
		MessageInfos:      file_protos_crawler_proto_msgTypes,
	}.Build()
	File_protos_crawler_proto = out.File
	file_protos_crawler_proto_goTypes = nil
	file_protos_crawler_proto_depIdxs = nil
}
